apiVersion: tracee.aquasec.com/v1beta1
kind: Policy
metadata:
    name: sample
spec:
    scope:
      - global
    rules:
      - event: execve
        filters:
        - podName=ubuntu
        - args.pathname=/usr/bin/ls
