# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: ubuntu
#   name: ubuntu
# spec:
#   replicas: 2
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 0
#   selector:
#     matchLabels:
#       app: ubuntu
#   template:
#     metadata:
#       labels:
#         app: ubuntu
#     spec:
#       securityContext:
#         seccompProfile:
#           type: Localhost
#           localhostProfile: profiles/updated.json
#       containers:
#       - name: ubuntu
#         image: ubuntu:latest
#         ports:
#         - containerPort: 80
#         command: ["sleep", "123456"]
#       imagePullSecrets:
#       - name: regcred
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ubuntu
    container: ubuntu-1
  name: ubuntu
spec:
  # securityContext:
  #   seccompProfile:
  #     type: Localhost
  #     localhostProfile: profiles/allow.json
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep", "123456"]
  imagePullSecrets:
  - name: regcred
